# Generated by Django 5.2.17 on 2026-08-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket assigned'), ('ticket_escalated', 'Ticket escalated'), ('task_due', 'Task due'), ('mentioned', 'Mentioned')], max_length=30, verbose_name='kind'),
        ),
    ]
