# Generated by Django 5.2.17 on 2026-09-05 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_grant_customer_knowledge_base_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')], verbose_name='color'),
        ),
    ]
