# Generated by Django 5.2.17 on 2026-08-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_seed_due_reminder_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name': 'quick reply',
                'verbose_name_plural': 'quick replies',
                'ordering': ('title',),
            },
        ),
    ]
