# Generated by Django 5.2.17 on 2026-08-28 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_quickreply'),
        ('tickets', '0006_ticketactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='body')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_internal_notes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='mentioned_in_notes', to=settings.AUTH_USER_MODEL, verbose_name='mentioned users')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='tickets.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'internal note',
                'verbose_name_plural': 'internal notes',
                'ordering': ('-created_at',),
            },
        ),
    ]
