# Generated by Django 5.2.17 on 2026-09-03 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_internalnote'),
        ('tickets', '0009_ticket_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_at'], name='task_due_at_idx'),
        ),
    ]
