# Generated by Django 5.2.17 on 2026-09-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handed_off_at', models.DateTimeField(blank=True, null=True, verbose_name='handed off at')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_session', to='tickets.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'chatbot session',
                'verbose_name_plural': 'chatbot sessions',
                'ordering': ('-created_at',),
            },
        ),
    ]
