# Generated by Django 5.2.17 on 2026-08-29 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_customer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('user_created', 'User created'), ('user_role_changed', 'User role changed'), ('user_status_changed', 'User status changed'), ('role_created', 'Role created'), ('role_renamed', 'Role renamed'), ('role_permissions_changed', 'Role permissions changed'), ('role_deleted', 'Role deleted')], max_length=30, verbose_name='action')),
                ('target_label', models.CharField(max_length=150, verbose_name='target label')),
                ('from_value', models.TextField(blank=True, verbose_name='from value')),
                ('to_value', models.TextField(blank=True, verbose_name='to value')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to='accounts.role', verbose_name='target role')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL, verbose_name='target user')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ('-created_at',),
            },
        ),
    ]
