# Generated by Django 5.2.17 on 2026-09-02 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_auditlog_action'),
        ('organization', '0006_grant_department_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.department', verbose_name='department'),
        ),
    ]
