# Generated by Django 5.2.17 on 2026-09-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_department'),
        ('organization', '0010_grant_branch_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.branch', verbose_name='branch'),
        ),
    ]
