# Generated by Django 5.2.17 on 2026-09-11 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_repair_admin_role_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='requires_two_factor',
            field=models.BooleanField(default=False, verbose_name='requires two-factor authentication'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='two-factor authentication enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='two-factor secret'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User created'), ('user_role_changed', 'User role changed'), ('user_status_changed', 'User status changed'), ('user_deleted', 'User deleted'), ('role_created', 'Role created'), ('role_renamed', 'Role renamed'), ('role_permissions_changed', 'Role permissions changed'), ('role_deleted', 'Role deleted'), ('portal_access_granted', 'Portal access granted'), ('portal_access_revoked', 'Portal access revoked'), ('two_factor_enabled', 'Two-factor authentication enabled'), ('two_factor_disabled', 'Two-factor authentication disabled'), ('two_factor_reset', 'Two-factor authentication reset by admin'), ('two_factor_recovery_code_used', 'Two-factor recovery code used')], max_length=30, verbose_name='action'),
        ),
        migrations.CreateModel(
            name='TwoFactorRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=64, verbose_name='code hash')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'recovery code',
                'verbose_name_plural': 'recovery codes',
                'ordering': ('-created_at',),
            },
        ),
    ]
