# Generated by Django 5.2.17 on 2026-09-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_two_factor_authentication'),
        ('customers', '0011_customer_legal_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to='customers.customer', verbose_name='target customer'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User created'), ('user_role_changed', 'User role changed'), ('user_status_changed', 'User status changed'), ('user_deleted', 'User deleted'), ('role_created', 'Role created'), ('role_renamed', 'Role renamed'), ('role_permissions_changed', 'Role permissions changed'), ('role_deleted', 'Role deleted'), ('portal_access_granted', 'Portal access granted'), ('portal_access_revoked', 'Portal access revoked'), ('two_factor_enabled', 'Two-factor authentication enabled'), ('two_factor_disabled', 'Two-factor authentication disabled'), ('two_factor_reset', 'Two-factor authentication reset by admin'), ('two_factor_recovery_code_used', 'Two-factor recovery code used'), ('data_retention_run', 'Scheduled data retention run'), ('customer_data_exported', 'Customer data exported'), ('customer_data_erased', 'Customer data erased')], max_length=30, verbose_name='action'),
        ),
    ]
