# Generated by Django 5.2.17 on 2026-08-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0006_ticketactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20, verbose_name='priority')),
                ('response_target_minutes', models.PositiveIntegerField(help_text='Minutes from ticket creation within which a first outbound reply is due.', verbose_name='response target (minutes)')),
                ('resolution_target_minutes', models.PositiveIntegerField(help_text='Minutes from ticket creation within which the ticket must reach resolved/closed.', verbose_name='resolution target (minutes)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='tickets.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'SLA policy',
                'verbose_name_plural': 'SLA policies',
                'ordering': ('priority', 'category__name'),
                'constraints': [models.UniqueConstraint(fields=('priority', 'category'), name='unique_sla_policy_priority_category')],
            },
        ),
    ]
