# Generated by Django 5.2.17 on 2026-08-27 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0001_initial'),
        ('tickets', '0006_ticketactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(choices=[('load', 'Least loaded agent'), ('round_robin', 'Round robin')], max_length=20, verbose_name='strategy')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('agents', models.ManyToManyField(blank=True, related_name='assignment_rules', to=settings.AUTH_USER_MODEL, verbose_name='candidate agents')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='tickets.category', verbose_name='category')),
                ('last_assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_assigned_rules', to=settings.AUTH_USER_MODEL, verbose_name='last assigned agent')),
            ],
            options={
                'verbose_name': 'assignment rule',
                'verbose_name_plural': 'assignment rules',
                'ordering': ('category__name',),
                'constraints': [models.UniqueConstraint(fields=('category',), name='unique_assignment_rule_category')],
            },
        ),
    ]
