# Generated by Django 5.2.17 on 2026-08-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0002_assignmentrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('at_risk', 'At risk of SLA breach'), ('idle', 'Idle (no recent activity)')], max_length=20, verbose_name='kind')),
                ('threshold_minutes', models.PositiveIntegerField(help_text="For 'at risk': minutes before an SLA deadline that counts as at-risk. For 'idle': minutes of no activity that counts as idle.", verbose_name='threshold (minutes)')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'escalation rule',
                'verbose_name_plural': 'escalation rules',
                'ordering': ('kind', 'threshold_minutes'),
            },
        ),
    ]
