# Generated by Django 5.2.17 on 2026-09-11 18:37
#
# `nulls_distinct=False` on both constraints: Postgres treats every NULL as
# distinct from every other by default, so a category-agnostic
# `SLAPolicy`/`AssignmentRule` "default" row was never actually unique
# despite the constraint names implying it was. Safe to apply directly — no
# duplicate default rows exist in this database (verified before writing
# this migration).

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sla", "0004_seed_escalation_schedule"),
        ("tickets", "0011_ticket_ticket_subject_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignmentrule",
            name="unique_assignment_rule_category",
        ),
        migrations.RemoveConstraint(
            model_name="slapolicy",
            name="unique_sla_policy_priority_category",
        ),
        migrations.AddConstraint(
            model_name="assignmentrule",
            constraint=models.UniqueConstraint(
                fields=("category",), name="unique_assignment_rule_category", nulls_distinct=False
            ),
        ),
        migrations.AddConstraint(
            model_name="slapolicy",
            constraint=models.UniqueConstraint(
                fields=("priority", "category"),
                name="unique_sla_policy_priority_category",
                nulls_distinct=False,
            ),
        ),
    ]
