# Generated by Django 5.2.17 on 2026-09-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_grant_calendar_permissions'),
        ('sla', '0005_enforce_single_default_policy_and_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='slapolicy',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_policies', to='organization.businesscalendar', verbose_name='business calendar'),
        ),
    ]
