# Generated by Django 5.2.17 on 2026-08-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='organization name')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='logo URL')),
                ('departments', models.JSONField(blank=True, default=list, verbose_name='departments')),
                ('branches', models.JSONField(blank=True, default=list, verbose_name='branches')),
                ('default_response_target_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='default response target (minutes)')),
                ('default_resolution_target_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='default resolution target (minutes)')),
            ],
            options={
                'verbose_name': 'organization settings',
                'verbose_name_plural': 'organization settings',
            },
        ),
    ]
