# Generated by Django 5.2.17 on 2026-09-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_migrate_settings_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='departments',
        ),
    ]
