# Generated by Django 5.2.17 on 2026-09-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_migrate_settings_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='branches',
        ),
    ]
