# Generated by Django 5.2.17 on 2026-09-03 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_grant_branch_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')], verbose_name='brand colour'),
        ),
    ]
