# Generated by Django 5.2.17 on 2026-09-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationsettings_primary_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_headline_en', models.CharField(blank=True, max_length=200, verbose_name='hero headline (English)')),
                ('hero_headline_ar', models.CharField(blank=True, max_length=200, verbose_name='hero headline (Arabic)')),
                ('hero_value_proposition_en', models.TextField(blank=True, verbose_name='value proposition (English)')),
                ('hero_value_proposition_ar', models.TextField(blank=True, verbose_name='value proposition (Arabic)')),
                ('hero_primary_cta_label_en', models.CharField(blank=True, max_length=60, verbose_name='primary CTA label (English)')),
                ('hero_primary_cta_label_ar', models.CharField(blank=True, max_length=60, verbose_name='primary CTA label (Arabic)')),
                ('hero_primary_cta_target', models.CharField(blank=True, choices=[('login', 'Log in'), ('contact', 'Contact form'), ('chat', 'Live chat')], max_length=20, verbose_name='primary CTA target')),
                ('hero_secondary_cta_label_en', models.CharField(blank=True, max_length=60, verbose_name='secondary CTA label (English)')),
                ('hero_secondary_cta_label_ar', models.CharField(blank=True, max_length=60, verbose_name='secondary CTA label (Arabic)')),
                ('hero_secondary_cta_target', models.CharField(blank=True, choices=[('login', 'Log in'), ('contact', 'Contact form'), ('chat', 'Live chat')], max_length=20, verbose_name='secondary CTA target')),
                ('features_title_en', models.CharField(blank=True, max_length=200, verbose_name='highlights section title (English)')),
                ('features_title_ar', models.CharField(blank=True, max_length=200, verbose_name='highlights section title (Arabic)')),
                ('cta_title_en', models.CharField(blank=True, max_length=200, verbose_name='CTA band title (English)')),
                ('cta_title_ar', models.CharField(blank=True, max_length=200, verbose_name='CTA band title (Arabic)')),
                ('cta_subtitle_en', models.TextField(blank=True, verbose_name='CTA band subtitle (English)')),
                ('cta_subtitle_ar', models.TextField(blank=True, verbose_name='CTA band subtitle (Arabic)')),
                ('cta_label_en', models.CharField(blank=True, max_length=60, verbose_name='CTA band button (English)')),
                ('cta_label_ar', models.CharField(blank=True, max_length=60, verbose_name='CTA band button (Arabic)')),
                ('cta_target', models.CharField(blank=True, choices=[('login', 'Log in'), ('contact', 'Contact form'), ('chat', 'Live chat')], max_length=20, verbose_name='CTA band target')),
                ('footer_text_en', models.CharField(blank=True, max_length=200, verbose_name='footer text (English)')),
                ('footer_text_ar', models.CharField(blank=True, max_length=200, verbose_name='footer text (Arabic)')),
            ],
            options={
                'verbose_name': 'landing content',
                'verbose_name_plural': 'landing content',
            },
        ),
        migrations.CreateModel(
            name='LandingHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=120, verbose_name='title (English)')),
                ('title_ar', models.CharField(max_length=120, verbose_name='title (Arabic)')),
                ('description_en', models.TextField(verbose_name='description (English)')),
                ('description_ar', models.TextField(verbose_name='description (Arabic)')),
                ('icon', models.CharField(choices=[('inbox', 'Inbox'), ('timer', 'Timer'), ('sparkles', 'Sparkles'), ('bar-chart-3', 'Bar chart'), ('message-square', 'Message'), ('users', 'People'), ('shield-check', 'Shield'), ('zap', 'Lightning'), ('globe', 'Globe'), ('clock', 'Clock'), ('file-text', 'Document'), ('bell', 'Bell')], default='sparkles', max_length=32, verbose_name='icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'landing highlight',
                'verbose_name_plural': 'landing highlights',
                'ordering': ('order', 'id'),
            },
        ),
    ]
