# Generated by Django 5.2.17 on 2026-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_landing_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('github', 'GitHub'), ('website', 'Website'), ('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='platform')),
                ('value', models.CharField(max_length=254, verbose_name='value')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'landing social link',
                'verbose_name_plural': 'landing social links',
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('platform',), name='unique_landing_social_platform')],
            },
        ),
    ]
