# Generated by Django 5.2.17 on 2026-09-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_landing_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='hero image URL'),
        ),
    ]
