# Generated by Django 5.2.17 on 2026-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_landing_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='retention_attachments_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='attachment retention (days)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='retention_audit_log_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='audit log retention (days)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='retention_closed_tickets_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='closed ticket retention (days)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='retention_messages_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='message retention (days)'),
        ),
    ]
