# Generated by Django 5.2.17 on 2026-09-12 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_organizationsettings_retention_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'business calendar',
                'verbose_name_plural': 'business calendars',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='organization.businesscalendar', verbose_name='business calendar'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='label')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.businesscalendar', verbose_name='calendar')),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
                'ordering': ('date',),
                'constraints': [models.UniqueConstraint(fields=('calendar', 'date'), name='unique_holiday_calendar_date')],
            },
        ),
        migrations.CreateModel(
            name='WorkingWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_windows', to='organization.businesscalendar', verbose_name='calendar')),
            ],
            options={
                'verbose_name': 'working window',
                'verbose_name_plural': 'working windows',
                'ordering': ('weekday', 'start_time'),
                'constraints': [models.UniqueConstraint(fields=('calendar', 'weekday'), name='unique_working_window_calendar_weekday')],
            },
        ),
    ]
