# Generated by Django 5.2.17 on 2026-09-02 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_customer_external_id"),
        ("integrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErpConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False, verbose_name="enabled")),
                ("base_url", models.URLField(blank=True, max_length=500, verbose_name="base URL")),
                (
                    "auth_token",
                    models.CharField(blank=True, max_length=500, verbose_name="auth token"),
                ),
                (
                    "export_enabled",
                    models.BooleanField(default=False, verbose_name="export enabled"),
                ),
                (
                    "customer_field_map",
                    models.JSONField(blank=True, default=dict, verbose_name="customer field map"),
                ),
                (
                    "order_field_map",
                    models.JSONField(blank=True, default=dict, verbose_name="order field map"),
                ),
                (
                    "customer_external_id_field",
                    models.CharField(
                        default="id", max_length=100, verbose_name="customer id field"
                    ),
                ),
                (
                    "order_external_id_field",
                    models.CharField(default="id", max_length=100, verbose_name="order id field"),
                ),
                (
                    "order_customer_ref_field",
                    models.CharField(
                        default="customer_id",
                        max_length=100,
                        verbose_name="order customer reference field",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last sync at"),
                ),
            ],
            options={
                "verbose_name": "ERP connection",
                "verbose_name_plural": "ERP connection",
            },
        ),
        migrations.CreateModel(
            name="ErpOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(max_length=100, unique=True, verbose_name="ERP external id"),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=100, verbose_name="order number"),
                ),
                ("status", models.CharField(blank=True, max_length=50, verbose_name="status")),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="total amount",
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3, verbose_name="currency")),
                (
                    "placed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="placed at"),
                ),
                ("raw", models.JSONField(blank=True, default=dict, verbose_name="raw payload")),
                ("synced_at", models.DateTimeField(verbose_name="synced at")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erp_orders",
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP order",
                "verbose_name_plural": "ERP orders",
                "ordering": ("-placed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ErpSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("import", "Import"), ("export", "Export")],
                        max_length=10,
                        verbose_name="direction",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                        verbose_name="state",
                    ),
                ),
                ("created_count", models.PositiveIntegerField(default=0, verbose_name="created")),
                ("updated_count", models.PositiveIntegerField(default=0, verbose_name="updated")),
                ("skipped_count", models.PositiveIntegerField(default=0, verbose_name="skipped")),
                ("failed_count", models.PositiveIntegerField(default=0, verbose_name="failed")),
                ("started_at", models.DateTimeField(verbose_name="started at")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finished at"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erp_sync_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="triggered by",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP sync run",
                "verbose_name_plural": "ERP sync runs",
                "ordering": ("-started_at",),
            },
        ),
    ]
