# Generated by Django 5.2.17 on 2026-09-02 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_seed_erp_sync_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("target_url", models.URLField(max_length=500, verbose_name="target URL")),
                ("secret", models.CharField(blank=True, max_length=255, verbose_name="secret")),
                ("events", models.JSONField(default=list, verbose_name="events")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_subscriptions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook subscription",
                "verbose_name_plural": "webhook subscriptions",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.CharField(max_length=50, verbose_name="event")),
                ("payload", models.JSONField(default=dict, verbose_name="payload")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("retrying", "Retrying"),
                            ("failed", "Failed"),
                        ],
                        max_length=10,
                        verbose_name="state",
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1, verbose_name="attempt")),
                (
                    "response_status_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="response status code"
                    ),
                ),
                ("response_body", models.TextField(blank=True, verbose_name="response body")),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.webhooksubscription",
                        verbose_name="subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook delivery",
                "verbose_name_plural": "webhook deliveries",
                "ordering": ("-created_at",),
            },
        ),
    ]
