# Generated by Django 5.2.17 on 2026-09-03 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_customer_name_idx'),
        ('integrations', '0004_webhooksubscription_webhookdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='erporder',
            index=models.Index(fields=['-placed_at', '-id'], name='erporder_placed_idx'),
        ),
        migrations.AddIndex(
            model_name='erpsyncrun',
            index=models.Index(fields=['-started_at'], name='erpsyncrun_started_idx'),
        ),
    ]
