# Generated by Django 5.2.17 on 2026-08-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_grant_customer_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='channel')),
                ('value', models.CharField(max_length=254, verbose_name='value')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'contact detail',
                'verbose_name_plural': 'contact details',
                'ordering': ('customer', 'channel', 'id'),
                'constraints': [models.UniqueConstraint(fields=('customer', 'channel', 'value'), name='unique_customer_channel_value')],
            },
        ),
    ]
