# Generated by Django 5.2.17 on 2026-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="ERP external id"
            ),
        ),
    ]
