# Generated by Django 5.2.17 on 2026-09-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_external_id'),
        ('organization', '0010_grant_branch_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='organization.branch', verbose_name='branch'),
        ),
    ]
