# Generated by Django 5.2.17 on 2026-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_customer_name_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_contact_enabled',
            field=models.BooleanField(default=True, verbose_name='email enabled for contact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_contact_enabled',
            field=models.BooleanField(default=True, verbose_name='phone enabled for contact (SMS)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='phone enabled for WhatsApp'),
        ),
    ]
