# Generated by Django 5.2.17 on 2026-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_email_contact_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='legal_hold',
            field=models.BooleanField(default=False, verbose_name='legal hold'),
        ),
    ]
