# Generated by Django 5.2.17 on 2026-09-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("host", models.CharField(blank=True, max_length=255, verbose_name="SMTP host")),
                ("port", models.PositiveIntegerField(default=587, verbose_name="SMTP port")),
                (
                    "host_user",
                    models.CharField(blank=True, max_length=255, verbose_name="SMTP username"),
                ),
                (
                    "host_password",
                    models.CharField(blank=True, max_length=255, verbose_name="SMTP password"),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="use TLS")),
                (
                    "default_from_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="from address"),
                ),
            ],
            options={
                "verbose_name": "email provider config",
                "verbose_name_plural": "email provider config",
            },
        ),
        migrations.CreateModel(
            name="SmsProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_base_url",
                    models.URLField(blank=True, max_length=500, verbose_name="API base URL"),
                ),
                (
                    "account_sid",
                    models.CharField(blank=True, max_length=100, verbose_name="account SID"),
                ),
                (
                    "auth_token",
                    models.CharField(blank=True, max_length=500, verbose_name="auth token"),
                ),
                (
                    "from_number",
                    models.CharField(blank=True, max_length=40, verbose_name="from number"),
                ),
            ],
            options={
                "verbose_name": "SMS provider config",
                "verbose_name_plural": "SMS provider config",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_base_url",
                    models.URLField(blank=True, max_length=500, verbose_name="API base URL"),
                ),
                (
                    "phone_number_id",
                    models.CharField(blank=True, max_length=100, verbose_name="phone number id"),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=500, verbose_name="access token"),
                ),
            ],
            options={
                "verbose_name": "WhatsApp provider config",
                "verbose_name_plural": "WhatsApp provider config",
            },
        ),
    ]
