# Generated by Django 5.2.17 on 2026-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_emailproviderconfig_smsproviderconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='target_address',
            field=models.CharField(blank=True, max_length=254, verbose_name='target address'),
        ),
    ]
