# Generated by Django 5.2.17 on 2026-09-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_message_target_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('web_form', 'Web form'), ('chat', 'Live chat')], max_length=20, verbose_name='channel'),
        ),
    ]
