# Generated by Django 5.2.17 on 2026-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalated',
            field=models.BooleanField(default=False, verbose_name='escalated'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='escalated at'),
        ),
    ]
