# Generated by Django 5.2.17 on 2026-08-27 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_escalated_ticket_escalated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('status_changed', 'Status changed'), ('assigned', 'Assignment changed')], max_length=20, verbose_name='kind')),
                ('from_value', models.CharField(blank=True, max_length=150, verbose_name='from value')),
                ('to_value', models.CharField(blank=True, max_length=150, verbose_name='to value')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tickets.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket activity',
                'verbose_name_plural': 'ticket activities',
                'ordering': ('-created_at',),
            },
        ),
    ]
