# Generated by Django 5.2.17 on 2026-09-02 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_grant_department_permissions'),
        ('tickets', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='organization.department', verbose_name='department'),
        ),
    ]
