# Generated by Django 5.2.17 on 2026-09-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_grant_branch_permissions'),
        ('tickets', '0008_ticket_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='organization.branch', verbose_name='branch'),
        ),
    ]
