# Generated by Django 5.2.17 on 2026-09-03 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_customer_name_idx'),
        ('organization', '0011_organizationsettings_primary_color'),
        ('tickets', '0009_ticket_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='ticket_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', '-created_at'], name='ticket_priority_created_idx'),
        ),
    ]
