# Generated by Django 5.2.17 on 2026-09-11 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0011_ticket_ticket_subject_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("is_shared", models.BooleanField(default=False, verbose_name="shared")),
                ("filters", models.JSONField(blank=True, default=dict, verbose_name="filters")),
                ("is_default", models.BooleanField(default=False, verbose_name="default")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "saved view",
                "verbose_name_plural": "saved views",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"), name="unique_saved_view_owner_name"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("owner",),
                        name="unique_saved_view_owner_default",
                    ),
                ],
            },
        ),
    ]
