# Generated by Django 5.2.17 on 2026-09-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0012_savedview"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_tickets",
                to="tickets.ticket",
                verbose_name="merged into",
            ),
        ),
        migrations.AlterField(
            model_name="ticketactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("status_changed", "Status changed"),
                    ("assigned", "Assignment changed"),
                    ("merged_into", "Merged into another ticket"),
                    ("merged_from", "Merged from another ticket"),
                ],
                max_length=20,
                verbose_name="kind",
            ),
        ),
    ]
