# Generated by Django 5.2.17 on 2026-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticket_merged_into_alter_ticketactivity_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='closed at'),
        ),
    ]
