# Generated by Django 5.2.17 on 2026-09-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pending_customer_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pending customer since'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='SLA paused minutes'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('pending_customer', 'Waiting on customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='status'),
        ),
    ]
